name: flutter_custom_credit_card_ui
description: Implement a flutter library to render a beautiful credit card ui.
version: 0.0.1
author: LyhourChhen
homepage: https://github.com/LyhourChhen/flutter_custom_credit_card_ui

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  credit_card_type_detector: ^1.0.2
  font_awesome_flutter: ^8.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

  assets:
    - assets/icons/creditCardStyleTop.png
    - assets/icons/creditCardStyleBottom.png