name: flutter_custom_credit_card_ui
description: A new Flutter package project.
version: 0.0.1
author: LyhourChhen
homepage: https://github.com/LyhourChhen/flutter_custom_credit_card_ui

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  credit_card_type_detector: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

  assets:
    - assets/creditCardStyleTop.png
    - assets/creditCardStyleBottom.png